# 1. np이름으로 numpy 패키지를 가져옵니다.

In [2]:
import numpy as np

# 3. 사이즈 10의 Null 벡터를 생성합니다.

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 6. 크기 10의 Null 벡터를 생성하되, 다섯 번째 값인 1을 만들어 출력합니다.

In [21]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 7. 값이 10~49인 벡터를 만드세요.

In [23]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 8. 벡터를 반전하세요(첫 번째 요소가 마지막이 됨/범위는 50).

In [25]:
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 9. 0 - 8 범위의 값을 사용하여 3x3 매트릭스 만들기

In [26]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 10. [1,2,0,0,4,0]에서 0이 아닌 요소의 index 찾기

In [27]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

# 11. 3x3 매트릭스 생성
- 매트릭스는 행렬을 이야기 한다.

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12. 랜덤 값이 있는 3x3x3 array 생성

In [33]:
# 첫번째 방법
np.random.randint(27, size=(3,3,3))

array([[[11, 14, 20],
        [14,  8, 21],
        [18, 23,  9]],

       [[13, 11,  8],
        [ 8, 18, 24],
        [20, 17, 25]],

       [[18,  6,  0],
        [18,  0,  1],
        [23, 13, 21]]])

In [34]:
# 두번째 방법
np.random.random((3,3,3))

array([[[0.08362562, 0.97974005, 0.00104994],
        [0.98073389, 0.31303268, 0.26998581],
        [0.77339605, 0.77919627, 0.39333259]],

       [[0.25033162, 0.47798529, 0.20757358],
        [0.1612314 , 0.85205881, 0.48066117],
        [0.12436824, 0.410063  , 0.79832144]],

       [[0.31770434, 0.0655597 , 0.88868498],
        [0.45355129, 0.99299692, 0.43592293],
        [0.54702519, 0.07094986, 0.5646335 ]]])

# 13. 랜덤 값이 있는 10x10 배열을 만들고 최소값과 최대값을 찾기

In [36]:
number = np.random.random((10,10))
print(number)
print(number.min())
print(number.max())

[[0.18582279 0.17594213 0.92575406 0.6857368  0.12285373 0.93109521
  0.35960067 0.54342372 0.29505461 0.19676024]
 [0.11670369 0.01860378 0.53703029 0.85195571 0.89155712 0.24017436
  0.29504791 0.34846988 0.66852061 0.05069638]
 [0.18693921 0.29652559 0.10217247 0.96781253 0.96737679 0.01543262
  0.39939835 0.87003321 0.74822006 0.56179623]
 [0.44139569 0.74969483 0.40768255 0.09985554 0.61108716 0.83695744
  0.77309871 0.12122395 0.09107627 0.61455197]
 [0.49250657 0.19361408 0.93009493 0.22514662 0.89288524 0.86010361
  0.68461281 0.79917336 0.40480874 0.18757446]
 [0.39380978 0.70077619 0.2064933  0.14193398 0.61688579 0.03694989
  0.61076174 0.34641215 0.22246314 0.46810427]
 [0.86875797 0.13730155 0.05193872 0.00389218 0.89970782 0.92658922
  0.08649319 0.80733588 0.81358722 0.44912611]
 [0.88545262 0.72545225 0.99212765 0.98476392 0.63269889 0.33945647
  0.14188368 0.15325324 0.39236924 0.94562368]
 [0.94121977 0.69726512 0.64744782 0.77354466 0.54024678 0.55701339
  0.46075437

# 14. 30 크기의 랜덤 벡터를 만들고 평균 값 찾기

In [58]:
# 첫번째 방법
number = np.random.randint(100, size = 30)
print(number)
np.mean(number)

[74 15 99 77 39 22 23 68 23 86 89 36 17 75 74 79  9 93 28 84 36 80 50 73
 54 15 35 24  9 14]


50.0

In [59]:
# 두번째 방법
a = np.random.random(30)
a.mean()

0.49202663153800696

# 15. 경계가 1이고 내부가 0인 2차원 배열 만들기

In [123]:
a = np.ones((10,10)) # 행은 가로,열은 세로
a[1:-1, 1:-1] = 0   # 0이 맨 첫번재이니까 -1은 맨 뒤에서 두번째이다.
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 16. 기존 어레이에 테두리를 0으로 채우는 방법

In [95]:
a = np.ones((10,10))
a[:,[0,-1]] = 0
a

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [96]:
a[[0,-1],:] = 0
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# 17. 어떤 결과가 나올지 생각해보기.

In [97]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

# 18. 대각선 값 1,2,3,4만을 출력, 5x5 매트릭스 모습.

In [108]:
np.diag(1 + np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 19. 8x8 매트릭스를 만들어 체크보드 패턴(숫자 1)으로 채우기

In [132]:
x = np.arange(64).reshape((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[ 0,  1,  2,  1,  4,  1,  6,  1],
       [ 1,  9,  1, 11,  1, 13,  1, 15],
       [16,  1, 18,  1, 20,  1, 22,  1],
       [ 1, 25,  1, 27,  1, 29,  1, 31],
       [32,  1, 34,  1, 36,  1, 38,  1],
       [ 1, 41,  1, 43,  1, 45,  1, 47],
       [48,  1, 50,  1, 52,  1, 54,  1],
       [ 1, 57,  1, 59,  1, 61,  1, 63]])

# 20. 100번째 원소의 색인(x,y,z)은 무엇입니까?(형상 배열(6,7,8)을 고려하시오.)

In [136]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

# 21. 타일 함수를 사용하여 체크보드 8X8 매트릭스 만들기

In [14]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 22. 5x5 랜덤 행렬 정규화하기

In [26]:
a = np.random.random((5,5))

#정규화 : 기본값 - 평균 / 표준편차
a_mean = a.mean()
a_std = a.std()
z = a_mean / a_std
a-z

array([[-1.75814263, -1.58264211, -1.30596511, -1.36383852, -1.84620383],
       [-1.06919672, -1.70320426, -1.41599332, -1.78677334, -1.5305226 ],
       [-1.03745383, -1.17395733, -1.89222109, -0.95761978, -1.69945226],
       [-0.93819941, -1.32470953, -1.19984117, -1.36752226, -1.15445366],
       [-1.19384852, -0.95520132, -1.0079267 , -1.03936199, -1.00411948]])

# 23. 색상을 4바이트(RGBA)로 나타내는 사용자 지정 dtype 생성하세요

In [2]:
import numpy as np
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                 ("b", np.ubyte, 1),
                 ("a", np.ubyte, 1)])

C:\Users\admin\AppData\Local\Temp\ipykernel_10224\2223963430.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


# 24. 5x3 매트릭스에 3x2 매트릭스를 곱합니다.

In [32]:
a = np.ones(15).reshape(5,3)
b = np.ones(6).reshape(3,2)
a@b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

# 25. 1차원 배열이 주어지면 3과 8사이의 모든 요소를 부정하기

In [6]:
a = np.arange(10)
print(a)
a = (a > 3) & (a < 8)
a

[0 1 2 3 4 5 6 7 8 9]


array([False, False, False, False,  True,  True,  True,  True, False,
       False])

# 29. 실수형 배열 0에서 반올림하는 방법

In [11]:
np.round(data, n)  #n은 몇 자리까지?

NameError: name 'data' is not defined

# 30. 두 어레이 간의 공통 값을 찾는 방법(어레이는 랜덤으로 만들기)

In [24]:
a1 = np.random.randint(1,10, size = 10)
a2 = np.random.randint(1,10, size = 10)
print(a1)
a2

[8 6 9 2 9 1 9 3 2 1]


array([3, 3, 6, 4, 3, 1, 3, 9, 2, 4])

In [25]:
b = list(set(a1)&set(a2))
b

[1, 2, 3, 6, 9]

# 33. 어제, 오늘 그리고 내일의 날짜를 알아보는법

In [26]:
from datetime import datetime

In [48]:
now = datetime.now() #오늘
print(now.strftime('%Y-%m-%d'))

2022-10-05


In [49]:
from datetime import datetime, timedelta   #timedelta

In [46]:
yesterday = datetime.today() - timedelta(1)  #어제
print(yesterday.strftime("%Y-%m-%d"))

2022-10-04


In [52]:
tomorrow = datetime.today() + timedelta(1)  #내일
print(tomorrow.strftime("%Y-%m-%d"))

2022-10-06


# 34. 2022년 10월에 해당하는 모든 날짜를 알아보기

In [57]:
import calendar
print(calendar.month(2022, 10))

    October 2022
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31



# 37. 행 값이 0~4인 5X5 매트릭스 만들기

In [78]:
a = np.random.randint(100, size = (5,5))
a

array([[99, 97, 70, 82, 60],
       [43, 37, 59, 17, 91],
       [99, 75, 41, 56, 98],
       [87, 68, 63, 17, 60],
       [82, 98, 12, 88, 50]])

In [79]:
a[:,0]=0
a

array([[ 0, 97, 70, 82, 60],
       [ 0, 37, 59, 17, 91],
       [ 0, 75, 41, 56, 98],
       [ 0, 68, 63, 17, 60],
       [ 0, 98, 12, 88, 50]])

In [80]:
a[:,1]=1
a[:,2]=2
a[:,3]=3
a[:,4]=4
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

# 38. 10개의 정수를 생성하고 이를 사용하여 배열을 만드는 함수를 구현하시오.

In [82]:
a = np.random.randint(100, size = 10)
a

array([26, 93, 51, 94, 34,  0, 88, 42, 11, 57])

In [99]:
def gen(x):
    for i in x:
        yield i+100
 
a = np.random.randint(100, size = 10)
for i in gen(a):
    print(i)

187
186
171
113
186
177
115
162
177
111


# 39. 0에서 1사이의 값으로 크기 10의 벡터를 만듭니다.(0,1 제외)

In [121]:
np.random.random(10)

array([0.85021579, 0.70650665, 0.43143861, 0.42299565, 0.1676873 ,
       0.06483389, 0.17298253, 0.07727225, 0.02285982, 0.61693421])

# 40. 크기 10의 랜덤 벡터를 만들어 정렬합니다.

In [125]:
a = np.random.random(10)
a.sort()
a

array([0.00224042, 0.18204029, 0.25407511, 0.51603985, 0.68407333,
       0.75429323, 0.81963024, 0.84514125, 0.85620271, 0.90168541])

# 42. 두 개의 랜덤 배열 A와 B를 고려하여 같은지 확인합니다.

In [127]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
(A==B).all()

False

# 45. 크기 10의 랜덤 벡터를 만들고 최대값을 0으로 바꿉니다.

In [136]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.81142462, 0.        , 0.87873217, 0.22215289, 0.28148142,
       0.78279814, 0.45749851, 0.88916601, 0.2468083 , 0.1189309 ])

# 58. 행렬의 각 행의 평균을 출력 하는법

In [140]:
a = np.random.rand(5,10)
a

array([[0.19943212, 0.13346823, 0.64400428, 0.37604402, 0.00687485,
        0.73693352, 0.03581034, 0.94780627, 0.05290889, 0.68784609],
       [0.72576704, 0.18557234, 0.95892171, 0.52350438, 0.36101935,
        0.17373627, 0.79000644, 0.37290916, 0.72373847, 0.91723373],
       [0.34775531, 0.08364195, 0.23072115, 0.43733268, 0.69757277,
        0.03688003, 0.1913443 , 0.79336031, 0.59243489, 0.7551193 ],
       [0.12860603, 0.12448624, 0.25129774, 0.23843507, 0.41675064,
        0.83554419, 0.83168602, 0.84781312, 0.64854768, 0.06354799],
       [0.87362773, 0.4526163 , 0.84612967, 0.8977848 , 0.85679883,
        0.43974973, 0.40352707, 0.73488985, 0.10622009, 0.44193538]])

In [141]:
a.mean(axis=1)

array([0.38211286, 0.57324089, 0.41661627, 0.43867147, 0.60532794])

# 60. 주어진 2D 배열에 null 열이 있는지 확인하는 방법

In [144]:
a = np.random.randint(0,3,(3,10))
a

array([[0, 0, 2, 0, 2, 1, 1, 1, 2, 2],
       [1, 0, 1, 0, 1, 0, 1, 2, 1, 1],
       [2, 2, 1, 1, 0, 2, 2, 2, 1, 0]])

In [148]:
((~a.any(axis=0)).any())

False