# 1. np이름으로 numpy 패키지를 가져옵니다.

In [7]:
import numpy as np

# 2. numpy 버전과 구성을 출력합니다.

In [137]:
np.__version__

'1.23.2'

# 3. 사이즈 10의 Null 벡터를 생성합니다.

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 4. 모든 배열의 메모리 크기 찾기/np.zeros((10,10))

In [138]:
z = np.zeros((10,10))
'%d bytes' % (z.size*z.itemsize)

'800 bytes'

# 5. 명령행에서 numpy add 기능의 설명서를 얻는 방법은 무엇입니까?

In [19]:
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 6. 크기 10의 Null 벡터를 생성하되, 다섯 번째 값인 1을 만들어 출력합니다.

In [21]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 7. 값이 10~49인 벡터를 만드세요.

In [23]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 8. 벡터를 반전하세요(첫 번째 요소가 마지막이 됨/범위는 50).

In [25]:
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 9. 0 - 8 범위의 값을 사용하여 3x3 매트릭스 만들기

In [26]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 10. [1,2,0,0,4,0]에서 0이 아닌 요소의 index 찾기

In [27]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

# 11. 3x3 매트릭스 생성
- 매트릭스는 행렬을 이야기 한다.

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12. 랜덤 값이 있는 3x3x3 array 생성

In [33]:
# 첫번째 방법
np.random.randint(27, size=(3,3,3))

array([[[11, 14, 20],
        [14,  8, 21],
        [18, 23,  9]],

       [[13, 11,  8],
        [ 8, 18, 24],
        [20, 17, 25]],

       [[18,  6,  0],
        [18,  0,  1],
        [23, 13, 21]]])

In [34]:
# 두번째 방법
np.random.random((3,3,3))

array([[[0.08362562, 0.97974005, 0.00104994],
        [0.98073389, 0.31303268, 0.26998581],
        [0.77339605, 0.77919627, 0.39333259]],

       [[0.25033162, 0.47798529, 0.20757358],
        [0.1612314 , 0.85205881, 0.48066117],
        [0.12436824, 0.410063  , 0.79832144]],

       [[0.31770434, 0.0655597 , 0.88868498],
        [0.45355129, 0.99299692, 0.43592293],
        [0.54702519, 0.07094986, 0.5646335 ]]])

# 13. 랜덤 값이 있는 10x10 배열을 만들고 최소값과 최대값을 찾기

In [36]:
number = np.random.random((10,10))
print(number)
print(number.min())
print(number.max())

[[0.18582279 0.17594213 0.92575406 0.6857368  0.12285373 0.93109521
  0.35960067 0.54342372 0.29505461 0.19676024]
 [0.11670369 0.01860378 0.53703029 0.85195571 0.89155712 0.24017436
  0.29504791 0.34846988 0.66852061 0.05069638]
 [0.18693921 0.29652559 0.10217247 0.96781253 0.96737679 0.01543262
  0.39939835 0.87003321 0.74822006 0.56179623]
 [0.44139569 0.74969483 0.40768255 0.09985554 0.61108716 0.83695744
  0.77309871 0.12122395 0.09107627 0.61455197]
 [0.49250657 0.19361408 0.93009493 0.22514662 0.89288524 0.86010361
  0.68461281 0.79917336 0.40480874 0.18757446]
 [0.39380978 0.70077619 0.2064933  0.14193398 0.61688579 0.03694989
  0.61076174 0.34641215 0.22246314 0.46810427]
 [0.86875797 0.13730155 0.05193872 0.00389218 0.89970782 0.92658922
  0.08649319 0.80733588 0.81358722 0.44912611]
 [0.88545262 0.72545225 0.99212765 0.98476392 0.63269889 0.33945647
  0.14188368 0.15325324 0.39236924 0.94562368]
 [0.94121977 0.69726512 0.64744782 0.77354466 0.54024678 0.55701339
  0.46075437

# 14. 30 크기의 랜덤 벡터를 만들고 평균 값 찾기

In [58]:
# 첫번째 방법
number = np.random.randint(100, size = 30)
print(number)
np.mean(number)

[74 15 99 77 39 22 23 68 23 86 89 36 17 75 74 79  9 93 28 84 36 80 50 73
 54 15 35 24  9 14]


50.0

In [59]:
# 두번째 방법
a = np.random.random(30)
a.mean()

0.49202663153800696

# 15. 경계가 1이고 내부가 0인 2차원 배열 만들기

In [123]:
a = np.ones((10,10)) # 행은 가로,열은 세로
a[1:-1, 1:-1] = 0   # 0이 맨 첫번재이니까 -1은 맨 뒤에서 두번째이다.
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 16. 기존 어레이에 테두리를 0으로 채우는 방법

In [95]:
a = np.ones((10,10))
a[:,[0,-1]] = 0
a

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [96]:
a[[0,-1],:] = 0
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# 17. 어떤 결과가 나올지 생각해보기.

In [97]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

# 18. 5x5 매트릭스 생성(대각선 바로 아래에 값 1,2,3,4를 사용).

In [108]:
np.diag(1 + np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 19. 8x8 매트릭스를 만들어 체크보드 패턴(숫자 1)으로 채우기

In [132]:
x = np.arange(64).reshape((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[ 0,  1,  2,  1,  4,  1,  6,  1],
       [ 1,  9,  1, 11,  1, 13,  1, 15],
       [16,  1, 18,  1, 20,  1, 22,  1],
       [ 1, 25,  1, 27,  1, 29,  1, 31],
       [32,  1, 34,  1, 36,  1, 38,  1],
       [ 1, 41,  1, 43,  1, 45,  1, 47],
       [48,  1, 50,  1, 52,  1, 54,  1],
       [ 1, 57,  1, 59,  1, 61,  1, 63]])

# 20. 100번째 원소의 색인(x,y,z)은 무엇입니까?(형상 배열(6,7,8)을 고려하시오.)

In [136]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)