In [10]:
import re
m = re.match('[A-z]+', "Life is too short")
print(m)

<re.Match object; span=(0, 4), match='Life'>


In [19]:
s = "black, blue and brown"
p = re.compile("black|blue")
print(re.findall(p, s)) 

['black', 'blue']


In [41]:
s= "http://naver.com, http://google.com, ftp://daum.net"
p = re.compile('\w+(?=:)')
re.findall(p,s)

['http', 'http', 'ftp']

In [57]:
s= "http://naver.com, http://google.com, ftp://daum.net"
p = re.compile('(?<=://)\S+')
re.findall(p,s)

['naver.com,', 'google.com,', 'daum.net']

In [59]:
data = '''
안녕하세요 그리고 그리고
안녕하세요 또 또
안녕하세요 그런데 그런데 
안녕하세요 끝 끝
''' 

p = re.compile(r"(?P<repeat>\w+)\s+(?P=repeat)")

for i in p.finditer(data):
    print(i) 

<re.Match object; span=(7, 14), match='그리고 그리고'>
<re.Match object; span=(21, 24), match='또 또'>
<re.Match object; span=(31, 38), match='그런데 그런데'>
<re.Match object; span=(46, 49), match='끝 끝'>


In [68]:
data = '''
안녕하세요 그리고 그리고
안녕하세요 또 또
안녕하세요 그런데 그런데 
안녕하세요 끝 끝
''' 

data = re.findall("\w+", data)
set(data)

{'그런데', '그리고', '끝', '또', '안녕하세요'}

In [69]:
import urllib.request as req

In [72]:
req.urlopen("http://daum.net")   # 접속만 한 것이다.

In [90]:
data = req.urlopen("http://daum.net").read().decode("utf-8")
# utf-8로 인해 우리가 읽을 수 있는 형태가 되었다.

In [101]:
p = re.compile("https://\S+[.]js")
li = re.findall(p, data)
for i in li:
    print(i)

https://t1.daumcdn.net/kas/static/na.min.js
https://t1.daumcdn.net/tiara/js/v1/tiara.min.js
https://t1.daumcdn.net/top/tiller-pc/lib/1636937121956/polyfill.min.js
https://t1.daumcdn.net/top/tiller-pc/h/production/20220915_111213/index.js
https://t1.daumcdn.net/kas/static/ba.min.js
https://t1.daumcdn.net/top/tiller-pc/1655174491872/tiller-pc-suggest.js


In [154]:
data = """<div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="true" class="M_704" style="display: block;"><span class="WoYOw">이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사장님 너무 친절하시고 빵이 진짜 맛있어요.. 미친 맛,,,,🥹가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요,,,??!?! 저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ …</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식…</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div> 
"""

In [152]:
p = re.compile("[가-힣][\d\w\s]*")
r = p.findall(data)

for i in r:
    print(i) 

이른 아침 문을 여는 빵집입니다
아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요
이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다
가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다
참고로 식빵 나오는 시간은 오전11시
시 입니다
빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다
우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요
그리고 무엇보다 빵이 정말 맛있어요
제주도에서 원탑입니다 여기보다 두배는 
내용 더보기      704   맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡도 주시고 친절하세요 인절미빵 강추입니다  
내용 더보기      704   인절미빵
먹물치즈빵 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요 빵이 대체로 다
맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다
내용 더보기      704   사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요   여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서
내용 더보기      704   성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주
내용 더보기      704   사장님 너무 친절하시고 빵이 진짜 맛있어요
미친 맛가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요 저희 동네에 있었음 매일 가고싶네요  309 

내용 더보기      704   재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식 309 

내용 더보기 



### 자주 쓰이는 패턴
- 전화번호

In [ ]:
010     -1234     -3434

In [ ]:
'010[-]\d{4}\d{4}'
"\d{2,3}[-]\d{3,4}[-]\d+"

- 이메일

In [ ]:
prince@naver.com    
hello@daum.net    
morning@company.co.kr

In [ ]:
'\S+@[\w+.\w+]+''

- 주민번호

In [ ]:
210203 - 2134576

In [ ]:
'\d{6}-\d{7}'

In [18]:
text = '''
http://www.google.com/

https://mail.google.com/

ftp://ftp.google.com/

''' 

In [19]:
import re
p = re.compile(".+:")
p.findall(text)

['http:', 'https:', 'ftp:']

In [21]:
p = re.compile(".+(?=:)")
p.findall(text)

['http', 'https', 'ftp']

In [22]:
text = '''apple: $50.24
banana: $35.25
pizza: $100
''' 

In [25]:
import re

p = re.compile("\d+.\d+")
p.findall(text)

['50.24', '35.25', '100']

In [30]:
import re

p = re.compile("\S\d.+")
p.findall(text)

['$50.24', '$35.25', '$100']

In [31]:
text = '''<p>이른 아침 문을 여는 빵집입니다</p>
<h1>아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요</h1>
<h5>이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다</h5>
<p>가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다</p>
<p>참고로 식빵 나오는 시간은 오전시시 입니다</pp>
''' 

In [49]:
import re

p = re.compile("(?<=<p>).+(?=</p>)")
p.findall(text)

['이른 아침 문을 여는 빵집입니다', '가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다']

# 배열 만들기

In [50]:
import numpy as np

In [53]:
a = np.array([0,1,2,3]) # 입력값이 2개 이상이면 리스트로 묶는다.
a

array([0, 1, 2, 3])

In [54]:
print(a)

[0 1 2 3]


In [57]:
a.shape # 1차원 자료 4개가 들어있다.

(4,)

In [60]:
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

(4,)
4
int32
1


In [58]:
li = [0,1,2,3]
np.array(li)

array([0, 1, 2, 3])

In [63]:
a = np.array([0,1,2,3,4.3])
a.dtype

dtype('float64')

In [64]:
a = np.array([0,1,2,3,4.3], dtype='int')
a.dtype

dtype('int32')

In [65]:
a

array([0, 1, 2, 3, 4])

강제로 int라고 타입을 정해줬기 때문에 소수였던 4.3은 열어보면 4로 바뀜.

In [67]:
a = np.array([0,1,2,3,4.3], dtype='float')
a

array([0. , 1. , 2. , 3. , 4.3])

소수로 바뀌어있다.

In [70]:
a.dtype

dtype('float64')

In [72]:
a = np.array([0,1,2,3,4.3], dtype='float32')
a

array([0. , 1. , 2. , 3. , 4.3], dtype=float32)

float64 였는데 float32로 강제로 바꿔주니 바뀌었다.

In [73]:
a = np.array([0,1,2,3,4.3], dtype='float16')
a.dtype

dtype('float16')

In [74]:
a = np.array([0,1,2,3,4.3], dtype='int16')
a.dtype

dtype('int16')

In [111]:
np.array([1,2,3,4], [5,6,7,8])

TypeError: Field elements must be 2- or 3-tuples, got '5'

오류 뜨는 이유: 리스트끼리 또 묶어줘야 한다. (중첩리스트)

In [112]:
np.array([[1,2,3,4], [5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- 2차원 만들기

In [114]:
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [115]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
np.arange(12).reshape(3,-1)    #-1뜻은 알아서 계산해줘 라는뜻

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [119]:
np.arange(24).reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [121]:
np.arange(36).reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [124]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
a+b   # 끼리끼리 더해준다.

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 6,  8],
       [10, 12]])

In [126]:
a**b

array([[    1,    64],
       [ 2187, 65536]])

In [128]:
print(a)
c = np.array([5,6])
c   # 이거 2개를 더해주면?

[[1 2]
 [3 4]]


array([5, 6])

In [129]:
a + c

array([[ 6,  8],
       [ 8, 10]])

In [130]:
c = np.array([5])
a + c

array([[6, 7],
       [8, 9]])

In [131]:
a + 5

array([[6, 7],
       [8, 9]])

In [157]:
a = np.arange(25).reshape(5,5)
print(a[4])

[20 21 22 23 24]


In [160]:
a = np.arange(25).reshape(5,5)
print(a[:, 1],a[:, 3])

[ 1  6 11 16 21] [ 3  8 13 18 23]


In [183]:
a = np.arange(25).reshape(5,5)
a[1::2, 0:3:2]

array([[ 5,  7],
       [15, 17]])