In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.2'

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
z = np.zeros((10))
z[5]=1
z

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [6]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [13]:
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [15]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [26]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.random.random(27).reshape(3,3,3)

array([[[0.22616733, 0.04224731, 0.31547643],
        [0.86084509, 0.28246976, 0.64580288],
        [0.77864392, 0.96498559, 0.89870792]],

       [[0.38017451, 0.75936338, 0.08751121],
        [0.00981826, 0.40009407, 0.2517857 ],
        [0.82667352, 0.26406555, 0.65474014]],

       [[0.27263733, 0.37910602, 0.44389672],
        [0.72150215, 0.23715153, 0.94574255],
        [0.75852188, 0.17746282, 0.53288159]]])

In [36]:
a = np.random.random(100).reshape(10,10)

print(a.min())
a.max()

0.02025207501990567


0.9960563360932086

In [37]:
np.random.random(30).mean()

0.5302617240088063

In [64]:
a = np.zeros(100).reshape(10,10)
a[::9,] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [75]:
a[:, 0::9] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [76]:
b = np.ones(100).reshape(10,10)
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [78]:
b[0::9,] = 0
b[:,::9] = 0
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [85]:
c = np.arange(25).reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
np.diag(1 + np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [111]:
x = np.zeros(64).reshape((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [1]:
import numpy as np

In [4]:
a = np.random.random((5,5))
a

array([[0.73031115, 0.65598267, 0.07219021, 0.16295688, 0.07355092],
       [0.28228351, 0.37277775, 0.73575629, 0.81471664, 0.76982956],
       [0.51009894, 0.25767949, 0.22633252, 0.9418236 , 0.0211788 ],
       [0.72328001, 0.97288927, 0.43876669, 0.43732542, 0.0382828 ],
       [0.58874499, 0.51064525, 0.57606444, 0.39999526, 0.01732116]])

In [6]:
#정규화 = 기본값 - 평균/표준편차

In [9]:
a_mean = a.mean()

In [10]:
a_std = a.std()

In [11]:
aa = a_mean/a_std

In [12]:
a-aa

array([[-0.83293599, -0.90726447, -1.49105693, -1.40029026, -1.48969622],
       [-1.28096363, -1.19046939, -0.82749085, -0.7485305 , -0.79341758],
       [-1.05314821, -1.30556766, -1.33691463, -0.62142355, -1.54206834],
       [-0.83996713, -0.59035787, -1.12448045, -1.12592172, -1.52496434],
       [-0.97450216, -1.05260189, -0.98718271, -1.16325188, -1.54592598]])

In [13]:
np.dtype([('r', np.ubyte,1),
         ('g', np.ubyte,1),
         ('b', np.ubyte,1),
         ('a', np.ubyte,1)])

C:\Users\admin\AppData\Local\Temp\ipykernel_1984\1783307252.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np.dtype([('r', np.ubyte,1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

# 25