# CHAPTER 3

## 내장 자료구조, 함수, 파일

### enumerate

In [3]:
li = ['foo','bar','baz']
mapping = {}

for i, v in enumerate(li):
    mapping[v] = i
    
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

### sorted
- 정렬

In [5]:
sorted([6,5,6,2,4,3,5,2,4])

[2, 2, 3, 4, 4, 5, 5, 6, 6]

### zip 
- 다른 순차 자료형과 짝지어줌

In [11]:
a = ['foo', 'bar', 'baz']
b = ['one', 'two', 'three']

zipping = zip(a,b)
list(zipping)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

- zip과 enumerate가 함께 사용 가능

In [13]:
for i, (c,d) in enumerate(zip(a, b)):
    print('{0}: {1},{2}'.format(i,c,d))

0: foo,one
1: bar,two
2: baz,three


### reversed
- 역순

In [19]:
a = [1,2,3,4,5]

list(reversed(a))

[5, 4, 3, 2, 1]

## 사전

In [20]:
empty_dict = {}
d1 = {'a' : 'some value', 'b':[1,2,3,4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

### keys

In [23]:
list(d1.keys())

['a', 'b']

### values

In [24]:
list(d1.values())

['some value', [1, 2, 3, 4]]

### update
- 다른 사전과 합치기

In [25]:
d1.update({'b':'foo', 'c':'12'})
d1

{'a': 'some value', 'b': 'foo', 'c': '12'}

## 집합

### set
- 집합 생성

In [26]:
set([1,2,3,4,4,5])

{1, 2, 3, 4, 5}

- 합집합 -> |

In [28]:
a = {1,2,3,4}
b = {3,4,5,6}

a|b

{1, 2, 3, 4, 5, 6}

- 교집합 -> intersection

In [29]:
a.intersection(b)

{3, 4}

## 리스트, 집합, 사전 표기법

In [ ]:
result = []
for val in collection:
    if condition:
        result.append(expr)

In [ ]:
expr for val in collection if condition  # 위 아래 같은 문장(리스트 표기법)

In [3]:
#중첩된 리스트 표기법

all_data = [['John','Emily','Michael','Mary','Steven'],
            ['Maria','Juan','Javier','Natalia','Pilar']]

In [21]:
a = [name for i in all_data for name in i
     if name.count('e') >= 2]

list(a)

['Steven']

In [22]:
a = [(1,2,3),(4,5,6),(7,8,9)]
c = [b for i in a for b in i]
c

[1, 2, 3, 4, 5, 6, 7, 8, 9]

## 익명함수

### lambda
- '익명 함수를 선언한다'
- (lambda 매개변수 : 표현식)(x,y의 각각 넣어줄 숫자)

In [29]:
def hap(x, y):
    return x + y

hap(10, 20)   # 이 식을 간단하게 하면 밑에처럼 쓸 수 있다.

30

In [30]:
(lambda x,y : x+y)(10,20)

30

In [ ]:
m = lambda x :x[0]  #이렇게도 쓰임

## 제너레이터

### Iterable
- 반복 가능한 객체
- 대표적인 iterable한 타입 : list, dict, set, str, bytes, tuple, range

### Iterator
- 값을 차례대로 꺼낼 수 있는 객체
- 파이썬 내장함수인 iter()를 사용해서 iterator 객체를 만들 수 있다.

### Generator
- 순회 가능한 객체를 생성하는 간단한 방법, 함수안에 yield 키워드를 사용
- yield 가 호출되면 암시적으로 return이 호출되며,

  한번 더 실행되면 실행되었던 yield 다음 코드가 실행된다.
- 특징
   1. iterable한 순서가 지정됨(모든 generator는 iterator)
   2. 무한한 순서가 있는 객체를 모델링할 수 있다.(for문에서 사용 가능)

In [40]:
a = {'A':1, 'B':2, 'C':3}

for key in a:
    print(key)

A
B
C


In [39]:
def number_generator():
    yield 0
    yield 1
    yield 2
    yield 3

for i in number_generator():
    print(i)

0
1
2
3


- 제너레이터 표현식

In [41]:
gen = (x**2 for x in range(100))

In [43]:
def make_gen():
    for x in range(100):
        yield x**2

gen와 make_gen은 동일한 코드이다.

### itertools 모듈
- 매개변수로 입력된 iterable 안에 있는 키를 확인 후,
  
  분류하여 동일한 키를 가진 element들을 해당 키를 기준으로
  그룹지어 리턴한다.

In [46]:
from itertools import groupby

a = [('Europe', 'Manchester'),
    ('Asia', 'Seoul'),
    ('Asia', 'Tokyo'),
    ('America', 'NewYork')]

In [48]:
m = lambda x :x[0]
g = groupby(a, m)

for key, group in g:
    print(key + ':', list(group))

Europe: [('Europe', 'Manchester')]
Asia: [('Asia', 'Seoul'), ('Asia', 'Tokyo')]
America: [('America', 'NewYork')]


In [83]:
name = ['Alan', 'Adam', 'Wes', 'Will', 'Steven']

first_name = lambda x : x[0]
g = groupby(name, first_name)

for first, group in g:
    print(first, ':', list(group))

A : ['Alan', 'Adam']
W : ['Wes', 'Will']
S : ['Steven']


# CHAPTER 4

## NumPy

### array
- 배열을 생성한다.

In [86]:
import numpy as np

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [87]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

```
arr1은 1차원 형태로 생성되었고
arr2는 해당 데이터로부터 형태를 추론해서 2차원 형태로 생성되었다.
```

- np.zeros()

In [88]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

- np.ones()

In [90]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

- np.arange()

In [92]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### astype('데이터타입')
- 데이터 타입을 명시해준다.

In [100]:
a = np.array(['1.25', '-9.6', '42'])

a = a.astype('float')
a

array([ 1.25, -9.6 , 42.  ])

### 슬라이싱 기초

In [101]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr[5:8]

array([5, 6, 7])

In [103]:
arr[5:8] = 12

In [104]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

리스트와의 중요한 차이점은 배열 조각은 원본 배열의 '뷰'라는 점이다.

즉, 데이터는 복사되지 않고 뷰에 대한 변경은 그대로 원본 배열에 반영된다.

### np.unique()
- 배열 내에서 중복된 원소를 제거하고 남은 원소를 정렬된 형태로 반환하는 함수

In [105]:
name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [106]:
np.unique(name)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

### np.random
- 난수 생성

In [108]:
a = np.random.normal(size = (4,4))
a

array([[-0.95251574, -2.33397988, -1.86659069, -0.99808454],
       [ 0.81976274, -1.91849312, -0.6951497 , -1.05566583],
       [ 1.07599734, -0.1356794 , -0.72891413, -0.96165884],
       [-0.49812924,  0.08643829, -0.42618419, -1.31830111]])

normal을 이용하여표준정규분포로부터 4X4크기의 표본 생성함