In [3]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd

In [5]:
arr = np.array(['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']*10) 
arr

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고',
       '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지',
       '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터',
       '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기',
       '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서',
       '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV',
       '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고',
       '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지',
       '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [6]:
#fit, transform 으로 바꾸기
encoder = LabelEncoder()
labels = encoder.fit_transform(arr)
labels

array([0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3,
       2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5,
       3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1,
       4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [7]:
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
iris_data = iris['data']
iris_label = iris['target']

In [11]:
#데이터 프레임으로 변환하기
iris_df = pd.DataFrame(data = iris_data, columns=iris['feature_names'])
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [43]:
#새로운 칼럼 만들기.(label)
iris_df['label'] = iris['target']
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [44]:
#map을 사용하여 딕셔너리로 이름 할당하기.  기억하기!!!!!  머신러닝에 추가하기
iris_df['label'].map({0:'setosa', 1:'versicolior', 2:'virginica'})
# iris_df['label'].map(label_mapping)도 같은 방식

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: label, Length: 150, dtype: object

In [45]:
iris_df['label'] = iris_df['label'].map({0:'setosa', 1:'versicolior', 2:'virginica'})
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

         label  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [46]:
d = {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
df = pd.DataFrame(d)
df

col1  col2  col3
0     1     2     3
1    11    22    33

In [47]:
#하나의 리스트로 변환하기
df.values.flatten().tolist()

[1, 2, 3, 11, 22, 33]

```
#행렬 정렬은 np.sort()와 같이 sort()를 호출하는 방식과 ndarray.sort()와 같이
#행렬 자체에서 sort()를 호출하는 방식이 있다. 두 방식의 차이는?
정렬된 상태로 보여줄 뿐이지 변하진 않고
sort는 변화가 된다.
```

In [49]:
#데이터를 학습/테스트 데이터로 분리하는 함수는?
model_selection

In [50]:
iris = load_iris()
iris_data = iris['data']
iris_label = iris['target']

#7:3으로 각각 나눠주세요.

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.3) 

# 진도

# One - Hot encoding

In [61]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [65]:
items = np.array(items).reshape(-1,1)
# 한줄로 쭉 서있는게 아니라 세로로 한줄로 들어가야한다.(열이 1개)
items

array([['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [67]:
encoder = OneHotEncoder()
one_hot_labels = encoder.fit_transform(items)
one_hot_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

Sparse  ->  희소행렬

In [70]:
one_hot_labels.toarray()  #이렇게 만드는게 목표

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [72]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
pd.get_dummies(items)  #array로 바꿀 필요 없이 API 사용하기

TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

# Cross Validation(교차검증)
- 크로스는 여러번 이라는 뜻
- 교차검증은 여러번 검증한다는 것(여러 경로는 통해서 검증)

In [77]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()                   # 파일부르기

iris_data = iris.data                # data(정보)와 target(매치대상) 저장
iris_label= iris.target

dt_clf=DecisionTreeClassifier()      # 의사결정 트리 

kfold = KFold(n_splits = 5)          # 5번 검증한다

In [78]:
cv_accuracy = []
n_iter = 0

for train_index, test_index in kfold.split(iris_data):
    print(train_index, test_index)
    print("---"*10)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
------------------------------
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 12

```
2개중 첫번째 인덱스는 4개에 대한 인덱스(train_data)
뒤에는 나머지 한개의 인덱스(test_data)
이렇게 1덩어리가 5개로 쪼개져있다.
```

```
0,1,2가 있는데 0,1은 50개씩 있는데 2가 5개밖에 없으면 train이나 test에 편중되어서
2가 없는 상태로 학습이 되어서 맞추지 못하는 상황이 생긴다.

즉, 비율을 맞춰야 한다.

0이 100개 1은 40개 2가 10로 편중된 데이터가 있다면 
100,40,10개 각각 7:3비율로 7은 train으로 3은 test로 골고루 분산되게끔 만들어야한다.

test_size = 0.3
```

k-fold : 5-fold CV

In [82]:
iris_data = iris.data
                # data(정보)와 target(매치대상) 저장
iris_label= iris.target


dt_clf = DecisionTreeClassifier()      # 의사결정 트리 
kfold = KFold(n_splits=5)

cv_accuracy = []

# KFold객체의 split( ) 호출하면 폴드 별 학습용, 검증용 테스트의 인덱스를 반환한다. 이거 중요함.  
for train_index, test_index  in kfold.split(iris_data): 
    
    # print(train_index, test_index)
    # print("---"*10)
    # kfold.split( )으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = iris_data[train_index], iris_data[test_index]
    y_train, y_test = iris_label[train_index], iris_label[test_index]

    
    dt_clf.fit(X_train , y_train)    
    pred = dt_clf.predict(X_test)
    
   
    accuracy = accuracy_score(y_test,pred)   
    cv_accuracy.append(accuracy)
 
    print("개별 검증 정확도: ", cv_accuracy)
    
print('평균 검증 정확도:', np.mean(cv_accuracy)) 

개별 검증 정확도:  [1.0]
개별 검증 정확도:  [1.0, 1.0]
개별 검증 정확도:  [1.0, 1.0, 0.8666666666666667]
개별 검증 정확도:  [1.0, 1.0, 0.8666666666666667, 0.9333333333333333]
개별 검증 정확도:  [1.0, 1.0, 0.8666666666666667, 0.9333333333333333, 0.7666666666666667]
평균 검증 정확도: 0.9133333333333333


p102, 103 줄인 모습

In [102]:
from sklearn.datasets import load_iris #데이터 불러오기
from sklearn.tree import DecisionTreeClassifier  #정해주기
from sklearn.metrics import accuracy_score #평가기준
from sklearn.model_selection import StratifiedKFold #층화된 kfold를 가져온다.

In [103]:
iris = load_iris()
features = X = iris_data = iris.data
labels = y = iris_label = iris.target

In [104]:
dt_clf = DecisionTreeClassifier()

In [105]:
s_kfold = StratifiedKFold(n_splits = 3)
cv_accuracy = []

In [94]:
for train_index, test_index in s_kfold.split(features, labels): #비율 다 감안해서 쪼갠것
    print(train_index)
    print(test_index)
    print()

[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34
  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  67  68  69
  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  90  91  92  93  94  95  96  97  98  99 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  34
  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104
 105 106 107 108 109 110 111 112 113 114 115 133 134 135 136 137 138 139
 140 141 142 143 144 14

In [107]:
from sklearn.datasets import load_iris #데이터 불러오기
from sklearn.tree import DecisionTreeClassifier  #정해주기
from sklearn.metrics import accuracy_score #평가기준
from sklearn.model_selection import StratifiedKFold #층화된 kfold를 가져온다.

iris = load_iris()
features = X = iris_data = iris.data
labels = y = iris_label = iris.target

dt_clf = DecisionTreeClassifier()

s_kfold = StratifiedKFold(n_splits = 3)
cv_accuracy = []

for train_index, test_index in s_kfold.split(features, labels):

    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    acc = accuracy_score(y_test, pred)  #이 두 개를 비교해서 정확도 보가
    cv_accuracy.append(acc)
    print("개별 정확도: ", acc)
    
print('정확도 모음: ', cv_accuracy)

개별 정확도:  0.98
개별 정확도:  0.92
개별 정확도:  1.0
정확도 모음:  [0.98, 0.92, 1.0]


In [101]:
np.mean(cv_accuracy).round(4)

0.9686

## cross_val_score() : 위의 for문 보다 간단하게 나타낼 수 있는 함수

In [108]:
from sklearn.model_selection import cross_val_score, cross_validate #교차검증 점수

In [110]:
iris = load_iris()
data = features = X = iris_data = iris.data
label = labels = y = iris_label = iris.target

dt_clf = DecisionTreeClassifier()

In [112]:
scores = cross_val_score(dt_clf, data, label, scoring = 'accuracy', cv = 3) #3번 쪼개기
scores

array([0.98, 0.94, 0.98])

In [114]:
np.mean(scores).round(4)

0.9667

# GridSearch

In [115]:
grid_parameters = {'max_depth':[1,2,3],
                  'min_samples_split': [2,3]}

In [116]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, train_test_split

In [120]:
iris = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state=121) 

dt_clf = DecisionTreeClassifier()

grid_parameters = {'max_depth':[1,2,3],
                  'min_samples_split': [2,3]}

grid_tree = GridSearchCV(dt_clf, param_grid=grid_parameters, cv=3, refit=True)

grid_tree.fit(X_train, y_train) #학습이 이루어짐

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [121]:
grid_tree.cv_results_

{'mean_fit_time': array([0.00064524, 0.00099897, 0.        , 0.00066511, 0.00033228,
        0.00065883]),
 'std_fit_time': array([4.56960388e-04, 4.22478799e-06, 0.00000000e+00, 4.70303127e-04,
        4.69909263e-04, 4.65981751e-04]),
 'mean_score_time': array([0.00068251, 0.        , 0.        , 0.00033204, 0.        ,
        0.00067147]),
 'std_score_time': array([0.00048311, 0.        , 0.        , 0.00046957, 0.        ,
        0.00047486]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'ma

In [124]:
pd.DataFrame(grid_tree.cv_results_).iloc[:,5:] 
#보기 좋게 데이터프레임으로 변경함

param_min_samples_split                                    params  \
0                       2  {'max_depth': 1, 'min_samples_split': 2}   
1                       3  {'max_depth': 1, 'min_samples_split': 3}   
2                       2  {'max_depth': 2, 'min_samples_split': 2}   
3                       3  {'max_depth': 2, 'min_samples_split': 3}   
4                       2  {'max_depth': 3, 'min_samples_split': 2}   
5                       3  {'max_depth': 3, 'min_samples_split': 3}   

   split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
0              0.700                0.7               0.70         0.700000   
1              0.700                0.7               0.70         0.700000   
2              0.925                1.0               0.95         0.958333   
3              0.925                1.0               0.95         0.958333   
4              0.975                1.0               0.95         0.975000   
5              0.975                1.0               0.95         0.975000   

   std_test_score  rank_test_score  
0    1.110223e-16                5  
1    1.110223e-16                5  
2    3.118048e-02                3  
3    3.118048e-02                3  
4    2.041241e-02                1  
5    2.041241e-02                1

In [122]:
grid_tree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

grid_parameters = {'max_depth':[1,2,3],

'min_samples_split': [2,3]} 에서 격자로 곱해줘서 가장 좋은걸 찾아줌

In [125]:
grid_tree.best_score_

0.975

In [127]:
pred = grid_tree.predict(X_test)
pred

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])

In [128]:
accuracy_score(y_test, pred)

0.9666666666666667

## 정규화(Normalization)

In [131]:
iris = iris['data']
iris_df = pd.DataFrame(iris)
iris_df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [132]:
iris_df.max()

0    7.9
1    4.4
2    6.9
3    2.5
dtype: float64

In [134]:
iris_df.min()

0    4.3
1    2.0
2    1.0
3    0.1
dtype: float64

In [138]:
def min_max(x):
    return (x - x.min()) / (x.max() - x.min())

In [139]:
iris_df.apply(min_max)

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [140]:
iris_df.apply(min_max).max()

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float64

In [142]:
iris_df.apply(lambda x:(x - x.min()) / (x.max() - x.min())) #람다식으로 다르게 표현함

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

## MinMaxScaler 사용하기

In [143]:
from sklearn.preprocessing import MinMaxScaler

In [144]:
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [146]:
iris_scaled = scaler.fit_transform(iris_df)
iris_scaled  #이렇게 써줘도 결과는 똑같다.

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [147]:
X_train, X_test = train_test_split(iris_data)

In [150]:
X_train

scaler.fit()
scaler.fit_transform(X_train)

1,2,1,2 ---> 10

array([[0.55555556, 0.13636364, 0.66101695, 0.58333333],
       [0.13888889, 0.54545455, 0.10169492, 0.04166667],
       [0.22222222, 0.13636364, 0.33898305, 0.41666667],
       [0.47222222, 0.        , 0.6779661 , 0.58333333],
       [0.19444444, 0.36363636, 0.10169492, 0.04166667],
       [0.55555556, 0.27272727, 0.69491525, 0.58333333],
       [0.36111111, 0.36363636, 0.52542373, 0.5       ],
       [0.66666667, 0.40909091, 0.57627119, 0.54166667],
       [0.63888889, 0.36363636, 0.57627119, 0.54166667],
       [0.33333333, 0.13636364, 0.50847458, 0.5       ],
       [0.47222222, 0.22727273, 0.69491525, 0.625     ],
       [0.16666667, 0.63636364, 0.06779661, 0.        ],
       [0.16666667, 0.40909091, 0.08474576, 0.04166667],
       [0.33333333, 0.09090909, 0.45762712, 0.375     ],
       [0.58333333, 0.27272727, 0.77966102, 0.83333333],
       [0.80555556, 0.36363636, 0.81355932, 0.625     ],
       [0.47222222, 0.54545455, 0.59322034, 0.625     ],
       [0.08333333, 0.54545455,

In [149]:
X_test

scaler.transform(x_test)
1,2,1,2 ----> 10? X

array([[5.7, 2.6, 3.5, 1. ],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3. , 1.4, 0.3],
       [5.2, 4.1, 1.5, 0.1],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.5, 4.2, 1.4, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 2. , 3.5, 1. ],
       [6.9, 3.1, 4.9, 1.5],
       [4.7, 3.2, 1.3, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [6.4, 3.2, 5.3, 2.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 3.3, 4.7, 1.6],
       [6.8, 2.8, 4.8, 1.4],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.1, 2.8, 4. , 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.8, 2.7, 3.9, 1.2],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6. , 3. , 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [6.5, 3.2, 5.1, 2. ],
       [5.4, 3.7, 1.5, 0.2],
       [6.3, 2.9, 5.6, 1.8],
       [7.7, 2.8, 6.7, 2. ],
       [4.9, 2

먼저 있는것을 정규화 시키고 쪼개라
쪼개놓고 각각 정규화 시키면 fit이 기준을 다르게 잡기 때문에 달라진다.
즉, fit은 한번만 해줘야한다.

In [ ]:
scaler.fit(x)
scaler.transformm(x)

## 표준화(Standardization)

In [ ]:
x - mu / sigma

In [152]:
def standardize(x):
    return (x - x.mean()) / x.std()

In [156]:
iris_df.apply(standardize).mean()  

0   -1.457168e-15
1   -1.638319e-15
2   -1.292300e-15
3   -5.543714e-16
dtype: float64

평균이 0이 나오면 잘 나온것
e-16 이런식으로 나오면 0으로 나온것임.

In [157]:
from sklearn.preprocessing import StandardScaler

In [158]:
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      