In [ ]:
비정형 데이터를 머신러닝에 적용시키기 위한 텍스트 분석의 일환 순서이다.
1. 텍스트 전처리 2. 피처 벡터화/추출 3. 머신러닝 모델 수립 및 학습/예측/평가

In [11]:
from nltk import word_tokenize
from nltk.stem import PorterStemmer

text =  "Now I am going to have dinner with my wife. Thanks for having me here." 
words = word_tokenize(text)

porter = PorterStemmer()
[porter.stem(word) for word in words] 

['now',
 'i',
 'am',
 'go',
 'to',
 'have',
 'dinner',
 'with',
 'my',
 'wife',
 '.',
 'thank',
 'for',
 'have',
 'me',
 'here',
 '.']

In [14]:
# 토큰화 하면 갯수는 몇 개?
sentence = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop. " 

words = word_tokenize(sentence)
len(words)

25

In [42]:
# 희소행렬 만들기
from scipy import sparse

# COO 형식
data = np.array([5,2,3])
row = np.array([2,2,3])
col = np.array([3,4,2])

from scipy import sparse
sparse.coo_matrix((data, (row, col)), (5,6)).toarray()

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [41]:
# CSR 형식
data = np.array([5,2,3])
row = np.array([2,2,3])
col = np.array([3,4,2])

from scipy import sparse
sparse.csr_matrix((data, (row, col)), (5,6)).toarray()

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [ ]:
텍스트 분석 패키지 중 주로 소셜 미디어 텍스트에 대한 감성분석을 제공하고,
뛰어난 감성 분석결과 및 빠른 수행시간으로 대용량 텍스트 데이터에
잘 사용되는 패키지는?
-> VADER

자연어를 기계가 이해할 수 있는 숫자의 나열인 벡터로 바꿔야 줘야한다.
-> 피처 벡터화

두 문장에서 같은 단어가 자주 나타나면 코사인 유사도가 높다.

KMeans 객체의 clusters_centers 속성은 0에서 1의 값을 가지며 
    0에 가까울수록 중심에 가까운 값이다. (O,X)  -> x

In [ ]:
array([[1, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 5, 2, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0]])

In [56]:
data = np.array([1, 2, 4, 5, 2, 3])
row_index = np.array([0, 2, 2, 5, 5, 6])
col = np.array([0, 1, 2, 3, 4, 2])

sparse.csr_matrix((data, col, row_index), shape=(5, 6)).toarray() 

array([[1, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 5, 2, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0]])

# 장르 속성을 이용한 영화 콘텐츠 기반 필터링

In [58]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

movies = pd.read_csv('tmdb_5000_movies.csv')
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [63]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [65]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [66]:
movies['genres'][0][0]

'['

문자열의 인덱싱을 하고 있다는 의미이다.

In [67]:
from ast import literal_eval

In [ ]:
literal_eval()
: 이 함수는 어떤 표현이 들어오면 스트링 속에는 파이썬에서 만든것만이 들어가야한다.
    그러면 strings, bytes, numbers, tuples, lists, dicts,
sets, booleans, and None. 이런식으로 바꿔주는 함수이다.

In [69]:
literal_eval(movies['genres'][0])[0]

{'id': 28, 'name': 'Action'}

In [70]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [78]:
movies_df = movies.iloc[:, [3,17,1,18,19,8,4,7]]
movies_df[:2]

id                                     title  \
0  19995                                    Avatar   
1    285  Pirates of the Caribbean: At World's End   

                                                                                                genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {...   
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]   

   vote_average  vote_count  popularity  \
0           7.2       11800  150.437577   
1           6.9        4500  139.082615   

                                                                                              keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "sp...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic is...   

                                                                                              overview  
0  In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, ...  
1  Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of t...

In [79]:
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [80]:
movies_df['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [92]:
# 겹치는 장르의 갯수가 많을수록 유사하다고 판단할 거다.
# 그러므로 영화의 장르가 뭔지 알아야한다.
for i in movies_df['genres'][0] :
    print(i['name'])

Action
Adventure
Fantasy
Science Fiction


In [94]:
movies_df['genres'] = movies_df['genres'].apply(lambda x : [y['name'] for y in x])

In [95]:
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [y['name'] for y in x])

In [97]:
movies_df[:2]

id                                     title  \
0  19995                                    Avatar   
1    285  Pirates of the Caribbean: At World's End   

                                          genres  vote_average  vote_count  \
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                   [Adventure, Fantasy, Action]           6.9        4500   

   popularity  \
0  150.437577   
1  139.082615   

                                                                                              keywords  \
0  [culture clash, future, space war, space colony, society, space travel, futuristic, romance, spa...   
1  [ocean, drug abuse, exotic island, east india trading company, love of one's life, traitor, ship...   

                                                                                              overview  
0  In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, ...  
1  Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of t...

In [98]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))

In [99]:
# 리스트는 안되서 문자열로 바꾸는 과정
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : " ".join(x))

In [102]:
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
genre_mat.shape

(4803, 276)

In [109]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(genre_mat, genre_mat) # 자기 자신과의 유사도이다.

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [110]:
genre_sim = cosine_similarity(genre_mat, genre_mat)

In [112]:
np.argsort(genre_sim)

array([[2401, 3037, 3038, ...,  813, 3494,    0],
       [2401, 3067, 3069, ...,  129,    1,  262],
       [2401, 2999, 3000, ..., 1542, 1740,    2],
       ...,
       [   0, 2230, 2229, ..., 1895, 3809, 4800],
       [   0, 3205, 3204, ..., 1596, 1594, 4802],
       [   0, 3141, 3140, ..., 4521, 4710, 4802]], dtype=int64)

In [125]:
genre_sim_sorted_ind = np.argsort(genre_sim)[:, ::-1]
genre_sim_sorted_ind

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]], dtype=int64)

In [ ]:
무엇을 의미하는가?

arg는 인덱스를 return해준다.
[2401, 3037, 3038, ...,  813, 3494,    0]와 
[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        , 를 보면
유사도가 낮은것부터 높은것으로 출력해주는것. 0은 밑에 출력물 1번의 인덱스이다.

즉, 0은 유사도가 가장 높은 인덱스 번호인 1을 나타내는 것이다.

In [116]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임. 
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes] 

In [124]:
df = movies_df.copy()
title_movie = df[df['title'] == 'The Godfather'] # The Godfather라는 조건을 걸어주었다.
title_movie

id          title          genres  vote_average  vote_count  \
3337  238  The Godfather  [Drama, Crime]           8.4        5893   

      popularity  \
3337  143.659698   

                                                                                                 keywords  \
3337  [italy, love at first sight, loss of father, patriarch, organized crime, mafia, lawyer, italian ...   

                                                                                                 overview  \
3337  Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime fa...   

     genres_literal  
3337    Drama Crime

In [126]:
find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather')

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                                                                                 keywords  \
2731  [italo-american, cuba, vororte, melancholy, praise, revenge, mafia, lawyer, blood, corrupt polit...   
1243                                         [epilepsy, protection money, secret love, money, redemption]   
3636                                           [suicide, drug dealer, redemption, addict, existentialism]   
1946     [police brutality, organized crime, policeman, illegal drugs, murder investigation, corrupt cop]   
2640  [father son relationship, bounty hunter, boat, way of life, coffin, denver, godmother, paranoia,...   
4065                                                                         [new york state, hate crime]   
1847  [prison, based on novel, florida, 1970s, mass murder, irish-american, drug traffic, biography, b...   
4217                                                                                [puberty, first time]   
883   [con man, biography, fbi agent, overhead camera shot, attempted jailbreak, engagement party, mis...   
3866  [male nudity, street gang, brazilian, photographer, 1970s, puberty, ghetto, gang war, coming of ...   

                                                                                                 overview  \
2731  In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily an...   
1243     A small-time hood must choose from among love, friendship and the chance to rise within the mob.   
3636  A drug dealer with upscale clientele is having moral problems going about his daily deliveries. ...   
1946  Terrence McDonagh, a New Orleans Police sergeant, who starts out as a good cop, receiving a meda...   
2640  A mafia film in Tarantino style with a star-studded cast. Jimmy’s “The Saint” gangster career ha...   
4065  A hate-crime has been committed in a the small city of Braxton, N.Y. Five migrant laborers have ...   
1847  The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbo...   
4217  A controversial portrayal of teens in New York City which exposes a deeply disturbing world of s...   
883   A true story about Frank Abagnale Jr. who, before his 19th birthday, successfully conned million...   
3866  Cidade de Deus is a shantytown that started during the 1960s and became one of Rio de Janeiro’s ...   

     genres_literal  
2731    Drama Crime  
1243    Drama Crime  
3636    Drama Crime  
1946    Drama Crime  
2640    Drama Crime  
4065    Drama Crime  
1847    Drama Crime  
4217    Drama Crime  
883     Drama Crime  
38

In [ ]:
# 가중치 주는 방식
(v / v+m) *R    +    (m/v+m) *C

In [128]:
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(.6)

In [129]:
C

6.092171559442011

In [130]:
m

370.1999999999998

In [144]:
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
        
    return ((v/(v+m)) * R) + ((m/(m+v)) * C)

In [146]:
movies_df['vote_count'] = movies_df['vote_count'].replace(0,1)

In [149]:
movies_df['weighted_vote'] = movies.apply(weighted_vote_average, axis=1)
movies_df['weighted_vote']

0       7.166301
1       6.838594
2       6.284091
3       7.541095
4       6.098838
          ...   
4798    6.290894
4799    6.089611
4800    6.106650
4801    6.084894
4802    6.100782
Name: weighted_vote, Length: 4803, dtype: float64

In [150]:
movies_df[['title', 'vote_average', 'weighted_vote', 'vote_count']].sort_values('weighted_vote', 
                                                                           ascending=False)[:10]

title  vote_average  weighted_vote  vote_count
1881  The Shawshank Redemption           8.5       8.396052        8205
3337             The Godfather           8.4       8.263591        5893
662                 Fight Club           8.3       8.216455        9413
3232              Pulp Fiction           8.3       8.207102        8428
65             The Dark Knight           8.2       8.136930       12002
1818          Schindler's List           8.3       8.126069        4329
3865                  Whiplash           8.3       8.123248        4254
809               Forrest Gump           8.2       8.105954        7927
2294             Spirited Away           8.3       8.105867        3840
2731    The Godfather: Part II           8.3       8.079586        3338

In [151]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출 
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
# 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출 
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average', 'weighted_vote']] 

title  vote_average  weighted_vote
2731       The Godfather: Part II           8.3       8.079586
1847                   GoodFellas           8.2       7.976937
3866                  City of God           8.1       7.759693
1663  Once Upon a Time in America           8.2       7.657811
883           Catch Me If You Can           7.7       7.557097
281             American Gangster           7.4       7.141396
4041              This Is England           7.4       6.739664
1149              American Hustle           6.8       6.717525
1243                 Mean Streets           7.2       6.626569
2839                     Rounders           6.9       6.530427

# Surprise를 이용한 추천 시스템 구축

In [1]:
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split

In [9]:
data = Dataset.load_builtin('ml-100k', prompt=False)

Trying to download dataset from http://files.grouplens.org/datasets/movielens/ml-100k.zip...
Done! Dataset ml-100k has been saved to C:\Users\admin/.surprise_data/ml-100k


In [10]:
trainset, testset = train_test_split(data, test_size=.25, random_state=0)

In [11]:
algo = SVD(random_state=0)
algo.fit(trainset)

In [17]:
preds = algo.test(testset)
preds[:5]

[Prediction(uid='120', iid='282', r_ui=4.0, est=3.5114147666251547, details={'was_impossible': False}),
 Prediction(uid='882', iid='291', r_ui=4.0, est=3.573872419581491, details={'was_impossible': False}),
 Prediction(uid='535', iid='507', r_ui=5.0, est=4.033583485472447, details={'was_impossible': False}),
 Prediction(uid='697', iid='244', r_ui=5.0, est=3.8463639495936905, details={'was_impossible': False}),
 Prediction(uid='751', iid='385', r_ui=4.0, est=3.1807542478219157, details={'was_impossible': False})]

In [19]:
[(pred.uid, pred.iid, pred.est) for pred in preds] [:3]

[('120', '282', 3.5114147666251547),
 ('882', '291', 3.573872419581491),
 ('535', '507', 4.033583485472447)]

In [22]:
pred = algo.predict(str(196), str(302))
pred

Prediction(uid='196', iid='302', r_ui=None, est=4.494386477040736, details={'was_impossible': False})

In [24]:
accuracy.rmse(preds)

RMSE: 0.9467


0.9466860806937948

In [28]:
import pandas as pd

ratings = pd.read_csv("ratings.csv")
ratings

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [29]:
ratings.to_csv('ratings_noh.csv', index=False, header=False)

In [39]:
from surprise import Reader

reader = Reader(line_format='user item rating timestamp', sep=',', rating_scale=(0.5, 5.0))

In [40]:
data = Dataset.load_from_file("ratings_noh.csv", reader=reader)

In [41]:
trainset, testset = train_test_split(data, test_size=.25, random_state=0)

In [42]:
algo = SVD(random_state=0)
algo.fit(trainset)

preds = algo.test(testset)
accuracy.rmse(preds)

RMSE: 0.8692


0.8691518972016722