In [4]:
import numpy as np
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.ones((2,3))  # 2행 3열을 ones로 채웠다.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.ones((2,3), dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# sparse matrix (희소행렬)
```
10X10 대부분 0.

3행3열 부분은 1
5행6열 부분도 1  100개 중 딱 2개만 1이다. 만들어보자.
```

In [16]:
a = np.zeros((10,10))
a[3,3] = 1
a[5,6] = 1

a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

```
모든 원소가 3인 10X10 array
```

In [28]:
np.full((10,10),3)  # 3으로 가득 채운다.

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [30]:
# 단위행렬
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(3)  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(3,2)   # 잡히는 대각선만 1로 잡는다.

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [37]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [39]:
b = a
b

[1, 2, 3, 4]

In [40]:
c = a.copy()
c

[1, 2, 3, 4]

In [42]:
import copy
d = copy.copy(a)
d

[1, 2, 3, 4]

In [45]:
b[0] = 100
b

[100, 2, 3, 4]

In [46]:
a

[100, 2, 3, 4]

In [47]:
c

[1, 2, 3, 4]

In [48]:
d

[1, 2, 3, 4]

In [50]:
print(id(a))
print(id(b))
print(id(c))
print(id(d))

2736421747520
2736421747520
2736421745984
2736421449344


In [52]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [53]:
b = a
b

array([1, 2, 3, 4])

In [54]:
c = a.copy()
c

array([1, 2, 3, 4])

In [55]:
import copy
d = copy.copy(a)
d

array([1, 2, 3, 4])

In [56]:
b[0]=100
b

array([100,   2,   3,   4])

In [57]:
a

array([100,   2,   3,   4])

In [58]:
c

array([1, 2, 3, 4])

In [59]:
d

array([1, 2, 3, 4])

In [60]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [61]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [63]:
np.ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [64]:
[0,10,20,30,40,50,60,70,80,90]

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [68]:
a = np.arange(10)*10
b = np.arange(10)*20
np.vstack((a,b))

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180]])

In [69]:
np.hstack((a,b))

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90,   0,  20,  40,
        60,  80, 100, 120, 140, 160, 180])

In [70]:
np.hstack((a,b)).shape

(20,)

In [74]:
a = np.array([[1],[2],[3]])
print(a.shape)
a

(3, 1)


array([[1],
       [2],
       [3]])

In [75]:
b = np.array([[1],[2],[3],])
b

array([[1],
       [2],
       [3]])

In [78]:
np.hstack((a,b))  #[[]] 이건 2차원 [[[]]]이건 3차원

array([[1, 1],
       [2, 2],
       [3, 3]])

In [79]:
np.dstack((a,b))

array([[[1, 1]],

       [[2, 2]],

       [[3, 3]]])

In [82]:
a = np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [83]:
np.hsplit(a,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [84]:
np.hsplit(a,4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [85]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

In [86]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [88]:
a.shape     #4행 8열

(4, 8)

In [90]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [92]:
a.flatten().shape   #,컴마 뒤에 아무것도 없으니 1차원이다.

(32,)

In [103]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [104]:
c = np.vstack((a,b))
np.vsplit(c,2) 

[array([[1, 2, 3]]), array([[4, 5, 6]])]

- 비교

In [107]:
a = np.array([1,2,3,4])
b = np.array([1,3,4,2])
a == b

array([ True, False, False, False])

In [108]:
a > 2

array([False, False,  True,  True])

In [109]:
a[a>2]

array([3, 4])

- 정렬(sort)

In [111]:
a = np.array([1,3,4,2])
np.sort(a)   

array([1, 2, 3, 4])

In [114]:
a   #sort는 단지 정렬해서 출력해준것

array([1, 3, 4, 2])

In [118]:
a[ : : -1 ]  # 거꾸로 출력

array([2, 4, 3, 1])

In [119]:
x = np.array([[2,1,6],
            [0,7,4],
            [5,3,2]])
x

array([[2, 1, 6],
       [0, 7, 4],
       [5, 3, 2]])

In [121]:
np.sort(x)  # 정렬되었다.

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [128]:
np.sort(x, axis = 0)  #행은 생각 안하고 열만 생각한 것임.

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

- Fancy Indexing

In [152]:
a = np.arange(8)*10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [158]:
a[[1,2,5]]

array([10, 20, 50])

In [159]:
indices = [1,2,-3]
a[indices]

array([10, 20, 50])

In [160]:
mask = [False, True, True, False, False, True, False, False]
a[mask]

array([10, 20, 50])

In [164]:
mask = np.array([0,1,1,0,0,1,0,0], dtype = bool)
a[mask]

array([10, 20, 50])

In [171]:
a =np.arange(25).reshape(5,5)
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

# 해보기

In [223]:
a = np.arange(100).reshape(10,10)
a = a[0:6:1,0:6:1]
a 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [225]:
#red
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [240]:
#yellow
a[[0],[3,4]]

array([3, 4])

In [264]:
#blue
a[4:,[4,5]]

array([[44, 45],
       [54, 55]])

In [287]:
#남색
a[[[2],[4]],[[0,2,4]]]

array([[20, 22, 24],
       [40, 42, 44]])

In [182]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
sum(a)

array([5, 7, 9])

In [187]:
np.sum(a)  # 통째로 다 집어넣었을때

21

In [192]:
np.sum(a, axis = 0)  # 가로로 합

array([5, 7, 9])

In [193]:
np.sum(a, axis = 1)   # 세로로 합

array([ 6, 15])

In [194]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [195]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [196]:
a**b

array([  1,  32, 729])

In [197]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [199]:
np.max(a)  # 전체 중 가장 큰 값을 출력함

3

- np.where()

In [200]:
a = np.array([6,7,8,9,10])
a

array([ 6,  7,  8,  9, 10])

In [202]:
a > 7

array([False, False,  True,  True,  True])

In [203]:
np.where(a>7)  # 2,3,4 이건 인덱스 번호이다.

(array([2, 3, 4], dtype=int64),)

In [205]:
a[np.where(a>7)]  # 8,9,10 이건 값이다.

array([ 8,  9, 10])

In [209]:
np.where(a>7, "pass", "fail")  # 파생변수 추가할때 많이 사용된다.

array(['fail', 'fail', 'pass', 'pass', 'pass'], dtype='<U4')

In [211]:
a = np.arange(-15,15).reshape(5,6)**2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [214]:
print(np.max(a))
print(np.sum(a)/len(a))
print(np.where (a < 10))

225
451.0
(array([2, 2, 2, 2, 2, 2, 3], dtype=int64), array([0, 1, 2, 3, 4, 5, 0], dtype=int64))


In [216]:
print(np.max(a[0]))
print(np.max(a[1]))
print(np.max(a[2]))
print(np.max(a[3]))
print(np.max(a[4]))

225
81
9
64
196


In [217]:
print(np.sum(a[0])/len(a))
print(np.sum(a[1])/len(a))
print(np.sum(a[2])/len(a))
print(np.sum(a[3])/len(a))
print(np.sum(a[4])/len(a))

191.0
54.2
3.8
39.8
162.2


In [221]:
a[np.where (a < 10)]

array([9, 4, 1, 0, 1, 4, 9])

```
10보다 작은 것은 모두 0으로, 크거나 같은 것은 1로 바꾸자.
np.where(a<10,,)
```

In [222]:
np.where(a < 10, 0,1)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])