In [21]:
########################## 연습문제

In [3]:
class Sport:
    def __init__(self, name, players):
        self.first = name
        self.second = players

In [6]:
class Sport:
    def __init__(self, name, players):
        self.name= name
        self.players = players 
        
    def explain(self):
        print(f'{self.name}는 한 팀당 {self.players}명이 하는 스포츠 입니다.')
        
soccer = Sport('축구', 11)
soccer.explain()

축구는 한 팀당 11명이 하는 스포츠 입니다.


In [17]:
class Plant:
    def __init__(self, name):
        self.name = name
        
    def color(self):
        self.color = 'green'
        return self.color
    

In [18]:
소나무 = Plant("소나무")

In [20]:
소나무.color()

'green'

In [25]:
class Apple(Plant):
    def color(self):
        self.color = 'Red'
        return self.color

In [26]:
사과 = Apple('홍옥')

In [27]:
사과.color()

'Red'

In [28]:
f = open("new.txt", 'w')
for i in range(10):
    f.write(f"Hello\n")
f.close() 

In [29]:
f = open('new.txt', 'r')
data  = f.readlines()       
for i in data:
    print(i)
    
f.close()

Hello

Hello

Hello

Hello

Hello

Hello

Hello

Hello

Hello

Hello



In [40]:
with open('gugu_txt', 'w') as f:
    for i in range(2,10):
        for a in range(1, 10):
            f.write(f'{i*a} ')
        f.write('\n')
            
f.close()

In [41]:
######################################

### 클래스 변수

In [53]:
class Family:
    lastname = '박'    # 클래스 변수
    
    def __init__(self, name):
        self.name = name      #인스턴스 변수

In [43]:
Family1 = Family('길동')

In [44]:
Family1.name

'길동'

In [45]:
Family1.lastname

'박'

In [46]:
Family.lastname

'박'

In [47]:
Family2 = Family('우치')

In [48]:
Family2.name

'우치'

In [49]:
Family2.lastname

'박'

In [52]:
id(Family1.lastname)

2973415672928

In [51]:
id(Family2.lastname)

2973415672928

같은 Family에 들어갔기 때문에 id가 같다.

In [60]:
name = '장길산'

class Family:
    lastname = '박'       # 클래스변수, 클래스변수는 인스턴스들이 공유한다.    
    
    def __init__(self, name):
        self.name = name   # 인스턴스변수, 지역변수
        
    def show_name(self):
        print(name)
        print(Family.lastname)
        print(self.lastname)
        print(self.name)

In [61]:
F1 = Family('길동')
F1.show_name()

장길산
박
박
길동


```
클래스 이름은 Person
name 전역변수 '아이유'
클래스변수 '손'
인스턴스 변수 입력받아서 "흥민"

세가지 변수를 모두 출력해 봅시다.
```

In [66]:
name = "아이유"

class Person:
    lastname = '손'
    
    def __init__(self, name):
        self.name = name
    
    def show_name(self):
        print(name)
        print(self.name)
        print(Person.lastname)
    
a = Person("흥민")
a.show_name()

아이유
흥민
손


### 상속 후 변수 추가

- 부모클래스에서 인자로 입력받는 것이 없을때

In [67]:
class Person:
    def __init__(self):
        self.name = "Lee"
        self.age = 25
    
class Korean(Person):
    pass

In [69]:
p1 = Person()
p1.name

'Lee'

In [70]:
k1 = Korean()
k1.name

'Lee'

In [71]:
class Korean(Person):
    def __init__(self):
        self.lang = '한국어'

In [72]:
k1 = Korean()
k1.lang

'한국어'

In [74]:
k1.name

AttributeError: 'Korean' object has no attribute 'name'

에러 이유 : def __init__(self) 이 부분이 문제가 된다.

부모 한테 상속 받은 것이 날라가버리고 오버라이딩

되버렸기 때문에 날라갔다.

In [75]:
class Korean(Person):
    def __init__(self):
        super().__init__()   # 부모클래스의 init 실행
        self.lang = '한국어'

초기화되면서 super()를 이용하여 그 함수를

한번 불러주는 역할을 한다.

In [76]:
k2 = Korean()

In [77]:
k2.lang

'한국어'

In [78]:
k2.name

'Lee'

```
American 클래스를 만들고, 쓰는 언어는 English로 합시다.
a1.lang 이것을 출력하면 English가 출력되야 한다.
```

In [83]:
class American:
    def __init__(self):
        super().__init__()
        self.lang = "English"
        
a1 = American()
a1.lang

'English'

- 부모클래스에서 인자로 입력받는 것이 있을때

In [106]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
class Korean(Person):
    def __init__(self):  
        super().__init__(name, age)
        self.lang = "한국어"


In [107]:
k1 = Korean("홍길동", 22)

TypeError: Korean.__init__() takes 1 positional argument but 3 were given

부모 클래스가 3개이니 자식 클래스도 3개를 써줘야 오류가 발생하지 않는다.

In [110]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

class Korean(Person):
    #def __init__(self):        잘못된 부분
    def __init__(self, name, age):    
        super().__init__(name, age)
        self.lang = "한국어"

In [112]:
k1 = Korean("홍길동", 22)
k1.name

'홍길동'

- 자식 클래스에서도 인자를 입력받는 경우

In [119]:
class Korean(Person):
    def __init__(self, lang, name, age):  # 모든 변수를 다 써준다.
        super().__init__(name, age)
        self.lang = lang

In [120]:
k1 = Korean("한국어", "길동", 22)

In [121]:
k1.lang

'한국어'

In [122]:
k1.name

'길동'

## 예외처리
- 에러처리    #except를 에러라고 읽어주기

In [143]:
a = ["Hello", "Good"]
for i in range(3):
    print(a[i])

Hello
Good


IndexError: list index out of range

헬로와 굿은 있지만 세번째는 없어서 에러가 발생했다.

In [146]:
a = ["Hello", "Good"]
try:
    for i in range(3):
        print(a[i])
except:           #에러는 이렇게 처리해줘! 라고 명령하는것
    print("에러입니다.")

Hello
Good
에러입니다.


In [148]:
print(4/2)
print(4/0)

2.0


ZeroDivisionError: division by zero

한 개는 되고 한 개는 안된 상황이다.

In [149]:
try:
    print(4/2)
    print(4/0)
except:
    print('에러입니다.')

2.0
에러입니다.


In [150]:
#try:
print(4/2)
print(4/0)
#except:
print('에러입니다.')

2.0


ZeroDivisionError: division by zero

ZeroDivisionError: division by zero 0으로 나눴다고 에러 뜸.

In [153]:
try:
    print(4/2)
    print(4/0)
except ZeroDivisionError as e :
    print(e)
    print('에러입니다.')

2.0
division by zero
에러입니다.


```
에러처리 방법

1. 일반적인 에러처리
2. 에러의 종류에 맞는 에러처리

현재 이렇게 2개의 처리 방법을 했다.
```

In [155]:
a = ["Hello", "Good"]
try:
    for i in range(3):
        print(a[i])
except:
    print("에러입니다")

Hello
Good
에러입니다


In [156]:
a = ["Hello", "Good"]
try:
    for i in range(3):
        print(a[i])
except IndexError as e:
    print(e) 

Hello
Good
list index out of range


## 내장함수

In [162]:
a = ['a','b','c']
for i in a:
    print(i)

a
b
c


인덱스까지 같이 보고싶다면 enumerate를 사용한다.

In [163]:
for i in enumerate(a):
    print(i)

(0, 'a')
(1, 'b')
(2, 'c')


In [164]:
for i, j in enumerate(a):
    print(i, j)

0 a
1 b
2 c


In [165]:
d = {'a':0, 'b':1, "c":2}

In [166]:
d

{'a': 0, 'b': 1, 'c': 2}

```
a = ['a','b','c'] 일때
위의 d와 같은 딕셔너리 c를 만들어라. (enumerate를 사용하여)
```

In [173]:
c = {}
for i, j in enumerate(a):
    c[j] = i
print(c) 

{'a': 0, 'b': 1, 'c': 2}


- filter
```
- filter(함수이름, 자료)
- 들어가는 함수는 참,거짓을 아웃풋으로 내야한다.
- 원소 하나하나에 대하여 함수를 적용시켜주는 함수 = map
```

In [180]:
a = [1, -3, 2, 0, -5, 6]
print(a > 0)

TypeError: '>' not supported between instances of 'list' and 'int'

리스트기 때문에 하나하나 비교하는게 아니라 리스트 즉 1개로 보기 때문에

오류가 발생한다.

그래서 필터를 사용하면 함수의 조건에 맞는 것을 하나하나 비교해주기 때문에 필요하다.

In [178]:
def positive(a):
    return a > 0    #참, 거짓으로 return값이 나온다.
positive(-3)

False

In [179]:
a = [1, -3, 2, 0, -5, 6]
list(filter(positive, a))

[1, 2, 6]

In [183]:
#lambda 함수 사용
a = [1, -3, 2, 0, -5, 6]
list(filter(lambda a: a>0, a))

[1, 2, 6]

In [184]:
#a = [1, -3, 2, 0, -5, 6]
#print(a > 0)

import numpy as np
a = np.array([1,-3, 2, 0, -5, 6])
a

array([ 1, -3,  2,  0, -5,  6])

In [186]:
a>0          # numpy를 사용하니 에러가 발생하지 않음.

array([ True, False,  True, False, False,  True])

In [187]:
a[ a>0 ]

array([1, 2, 6])